language: python
dist: xenial
sudo: true
python:
  - '3.6'
  - '3.7'
script:
  - python -m pytest test.py
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PW
  distributions: "sdist bdist_wheel"
